sudo: false
language: cpp
compiler:
  - gcc
addons:
 apt:
  sources:
  - ubuntu-toolchain-r-test
  packages:
  -  g++
  -  make 
  -  cmake 
  -  automake 
  -  unzip 
  -  git 
  -  build-essential 
  -  libtool 
  -  libssl-dev 
  -  libdb++-dev 
  -  libboost-all-dev 
  -  libcurl4-gnutls-dev
  -  miniupnpc 
  -  libminiupnpc-dev
  -  libevent-dev
  -  libjansson-dev

before_script:
 - cd libjl777
 - make -j8 onetime

script:
 - echo "Start make SuperNET"
 - make -j8 SuperNET
 - echo "Start make BTCD"
 - make -j8 btcd

#  - clang
# Install dependencies
# install: make get-deps
#install: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get -qq update && sudo apt-get -qq install g++-4.8 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90 && export CXX=g++ && export CC=g++ && g++ --version && gcc --version && sudo rm /usr/bin/gcc && sudo ln -s /usr/bin/g++-4.8 /usr/bin/gcc && gcc --version && cd libjl777 && make onetime
#install: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get -qq update && sudo apt-get -qq install g++-4.8 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90 && gcc --version && g++ --version && sudo apt-get -qq install make cmake automake unzip git gcc g++ clang build-essential libtool libssl-dev libdb++-dev libboost-all-dev libcurl4-gnutls-dev miniupnpc libminiupnpc-dev && cd libjl777 && make onetime
# Build and test
#script: echo "Start make SuperNET" && make SuperNET && echo "Start make btcd" && make btcd
